/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_torquewavez_FastLZ */

#ifndef _Included_nl_torquewavez_FastLZ
#define _Included_nl_torquewavez_FastLZ
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_torquewavez_FastLZ
 * Method:    compress
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nl_torquewavez_FastLZ_compress
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     nl_torquewavez_FastLZ
 * Method:    decompress
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nl_torquewavez_FastLZ_decompress
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
